name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Backend Dependencies
      run: cd backend && npm install

    - name: Run Backend Lint
      run: cd backend && npm run lint

    - name: Install Frontend Dependencies
      run: cd frontend && npm install

    - name: Run Frontend Lint
      run: cd frontend && npm run lint 